//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteUds.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoPersonalizacao = new HashSet<PedidoPersonalizacao>();
        }
    
        public int Id { get; set; }
        public int SaborId { get; set; }
        public int TamanhoId { get; set; }
    
        public virtual Sabor Sabor { get; set; }
        public virtual Tamanho Tamanho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoPersonalizacao> PedidoPersonalizacao { get; set; }
    }
}
