//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteUds.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personalizacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personalizacao()
        {
            this.PedidoPersonalizacao = new HashSet<PedidoPersonalizacao>();
        }
    
        public int Id { get; set; }
        public string Personalizacao1 { get; set; }
        public Nullable<int> Tempo { get; set; }
        public decimal Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoPersonalizacao> PedidoPersonalizacao { get; set; }
    }
}
